networks:
  default: avax-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.16
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3"

reports:
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
